# ifdef CONFIG_PRODUCT_REALME_RMX1801 
# geyixue@BSP.Driver, 2014/07/29, Add for OPPO device info
obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project.o boot_mode.o
# endif /* CONFIG_PRODUCT_REALME_RMX1801 */